api_platform:
    title: StreamPulse API
    version: 1.0.0
    show_webby: true
    enable_swagger_ui: true
    enable_re_doc: true
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_client_enabled: true
        pagination_client_items_per_page: true
        pagination_items_per_page: 30
        pagination_maximum_items_per_page: 1000
        formats:
            jsonld: ['application/ld+json']
            json: ['application/json']
            html: ['text/html']
        patch_formats:
            jsonpatch: ['application/json-patch+json']
            merge_patch: ['application/merge-patch+json']
