-- =============================================================================
-- StreamPulse (TVAPP) — full database schema for Supabase (PostgreSQL 16)
-- =============================================================================
-- Paste this into the Supabase SQL Editor and run it against a fresh database.
--
-- It reproduces the final state of the Doctrine migrations:
--   Version20260220063748  (initial schema)
--   Version20260220101957  (user_favorites + channel.view_count)
--   Version20260416134613  (pending_payment + channel.is_working)
--   Version20260630000000  (active_session + connection-limit columns)
--   Version20260710063121  (torrent_session)
--   Version20260722053848  (watch_history)
--   Version20260728123901  (adult-content lock: user + device columns)
--
-- Notes
--  * Column types / index names / constraint names match Doctrine exactly, so
--    the running Symfony app detects no schema drift.
--  * UUIDs are generated by the application (Symfony Uid), so columns carry no
--    server-side default.
--  * The doctrine_migration_versions table is pre-seeded at the bottom so the
--    container entrypoint's `doctrine:migrations:migrate` becomes a no-op
--    instead of trying to re-create these tables.
-- =============================================================================

BEGIN;

-- -----------------------------------------------------------------------------
-- Tables (no FKs yet — added afterwards so creation order does not matter)
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS category (
    id          UUID         NOT NULL,
    name        VARCHAR(255) NOT NULL,
    slug        VARCHAR(255) NOT NULL,
    description VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS "user" (
    id                       UUID         NOT NULL,
    email                    VARCHAR(180) NOT NULL,
    roles                    JSON         NOT NULL,
    password                 VARCHAR(255) NOT NULL,
    full_name                VARCHAR(255) DEFAULT NULL,
    country                  VARCHAR(2)   DEFAULT NULL,
    is_active                BOOLEAN      DEFAULT true NOT NULL,
    max_devices_override     INT          DEFAULT NULL,
    max_connections_override INT          DEFAULT NULL,
    adult_lock_password_hash VARCHAR(255) DEFAULT NULL,
    adult_lock_salt          VARCHAR(64)  DEFAULT NULL,
    adult_lock_updated_at    TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS package (
    id              UUID          NOT NULL,
    name            VARCHAR(255)  NOT NULL,
    description     VARCHAR(1024) DEFAULT NULL,
    price           DOUBLE PRECISION NOT NULL,
    max_devices     INT           NOT NULL,
    is_active       BOOLEAN       NOT NULL,
    max_connections INT           DEFAULT 1 NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS channel (
    id             UUID         NOT NULL,
    nanoid         VARCHAR(255) DEFAULT NULL,
    name           VARCHAR(255) NOT NULL,
    slug           VARCHAR(255) DEFAULT NULL,
    language       VARCHAR(10)  DEFAULT NULL,
    country        VARCHAR(100) DEFAULT NULL,
    is_geo_blocked BOOLEAN      NOT NULL,
    logo           VARCHAR(2048) DEFAULT NULL,
    is_active      BOOLEAN      NOT NULL,
    created_at     TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    category_id    UUID         DEFAULT NULL,
    view_count     INT          DEFAULT 0 NOT NULL,
    is_working     BOOLEAN      DEFAULT true NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS channel_stream (
    id         UUID          NOT NULL,
    type       VARCHAR(255)  NOT NULL,
    url        VARCHAR(1024) NOT NULL,
    channel_id UUID          NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS device (
    id                        UUID         NOT NULL,
    device_id                 VARCHAR(255) NOT NULL,
    device_name               VARCHAR(255) DEFAULT NULL,
    last_active_at            TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    user_id                   UUID         NOT NULL,
    adult_content_unlocked    BOOLEAN      DEFAULT false NOT NULL,
    adult_content_unlocked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS subscription (
    id         UUID    NOT NULL,
    start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    end_date   TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    is_active  BOOLEAN NOT NULL,
    user_id    UUID    NOT NULL,
    package_id UUID    NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS package_channel (
    package_id UUID NOT NULL,
    channel_id UUID NOT NULL,
    PRIMARY KEY (package_id, channel_id)
);

CREATE TABLE IF NOT EXISTS user_favorites (
    user_id    UUID NOT NULL,
    channel_id UUID NOT NULL,
    PRIMARY KEY (user_id, channel_id)
);

CREATE TABLE IF NOT EXISTS pending_payment (
    id         UUID        NOT NULL,
    reference  VARCHAR(64) NOT NULL,
    processed  BOOLEAN     DEFAULT false NOT NULL,
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    user_id    UUID        NOT NULL,
    package_id UUID        NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS active_session (
    id                UUID        NOT NULL,
    user_id           UUID        NOT NULL,
    device_id         UUID        NOT NULL,
    token             VARCHAR(64) NOT NULL,
    started_at        TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    last_heartbeat_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS torrent_session (
    id            UUID        NOT NULL,
    session_id    VARCHAR(36) NOT NULL,
    status        VARCHAR(30) NOT NULL,
    stream_token  VARCHAR(64) NOT NULL,
    created_at    TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    last_activity TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    user_id       UUID        NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS watch_history (
    id         INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tmdb_id    INT          NOT NULL,
    type       VARCHAR(20)  NOT NULL,
    season     INT          DEFAULT NULL,
    episode    INT          DEFAULT NULL,
    imdb_id    VARCHAR(30)  DEFAULT NULL,
    title_name VARCHAR(200) DEFAULT NULL,
    poster_url VARCHAR(500) DEFAULT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    user_id    UUID         NOT NULL,
    PRIMARY KEY (id)
);

-- -----------------------------------------------------------------------------
-- Indexes
-- -----------------------------------------------------------------------------

CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_8D93D649E7927C74  ON "user" (email);

CREATE INDEX        IF NOT EXISTS IDX_A2F98E4712469DE2   ON channel (category_id);
CREATE INDEX        IF NOT EXISTS IDX_E8A846272F5A1AA    ON channel_stream (channel_id);
CREATE INDEX        IF NOT EXISTS IDX_92FB68EA76ED395    ON device (user_id);

CREATE INDEX        IF NOT EXISTS IDX_A3C664D3A76ED395   ON subscription (user_id);
CREATE INDEX        IF NOT EXISTS IDX_A3C664D3F44CABFF   ON subscription (package_id);

CREATE INDEX        IF NOT EXISTS IDX_2DA2EBCBF44CABFF   ON package_channel (package_id);
CREATE INDEX        IF NOT EXISTS IDX_2DA2EBCB72F5A1AA   ON package_channel (channel_id);

CREATE INDEX        IF NOT EXISTS IDX_E489ED11A76ED395   ON user_favorites (user_id);
CREATE INDEX        IF NOT EXISTS IDX_E489ED1172F5A1AA   ON user_favorites (channel_id);

CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_A647739CAEA34913  ON pending_payment (reference);
CREATE INDEX        IF NOT EXISTS IDX_A647739CA76ED395   ON pending_payment (user_id);
CREATE INDEX        IF NOT EXISTS IDX_A647739CF44CABFF   ON pending_payment (package_id);

CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_ACTIVE_SESSION_TOKEN ON active_session (token);
CREATE INDEX        IF NOT EXISTS IDX_ACTIVE_SESSION_USER   ON active_session (user_id);
CREATE INDEX        IF NOT EXISTS IDX_ACTIVE_SESSION_DEVICE ON active_session (device_id);

CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_11AF26F3613FECDF ON torrent_session (session_id);
CREATE UNIQUE INDEX IF NOT EXISTS UNIQ_11AF26F3105F4450 ON torrent_session (stream_token);
CREATE INDEX        IF NOT EXISTS IDX_11AF26F3A76ED395  ON torrent_session (user_id);

CREATE INDEX        IF NOT EXISTS IDX_DE44EFD8A76ED395  ON watch_history (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS user_tmdb_season_episode_unique ON watch_history (user_id, tmdb_id, type, season, episode);

-- -----------------------------------------------------------------------------
-- Foreign keys
-- -----------------------------------------------------------------------------

ALTER TABLE channel         ADD CONSTRAINT FK_A2F98E4712469DE2 FOREIGN KEY (category_id) REFERENCES category (id);
ALTER TABLE channel_stream  ADD CONSTRAINT FK_E8A846272F5A1AA  FOREIGN KEY (channel_id)  REFERENCES channel (id);
ALTER TABLE device          ADD CONSTRAINT FK_92FB68EA76ED395  FOREIGN KEY (user_id)     REFERENCES "user" (id);

ALTER TABLE subscription    ADD CONSTRAINT FK_A3C664D3A76ED395 FOREIGN KEY (user_id)     REFERENCES "user" (id);
ALTER TABLE subscription    ADD CONSTRAINT FK_A3C664D3F44CABFF FOREIGN KEY (package_id)  REFERENCES package (id);

ALTER TABLE package_channel ADD CONSTRAINT FK_2DA2EBCBF44CABFF FOREIGN KEY (package_id)  REFERENCES package (id) ON DELETE CASCADE;
ALTER TABLE package_channel ADD CONSTRAINT FK_2DA2EBCB72F5A1AA FOREIGN KEY (channel_id)  REFERENCES channel (id) ON DELETE CASCADE;

ALTER TABLE user_favorites  ADD CONSTRAINT FK_E489ED11A76ED395 FOREIGN KEY (user_id)     REFERENCES "user" (id) ON DELETE CASCADE;
ALTER TABLE user_favorites  ADD CONSTRAINT FK_E489ED1172F5A1AA FOREIGN KEY (channel_id)  REFERENCES channel (id) ON DELETE CASCADE;

ALTER TABLE pending_payment ADD CONSTRAINT FK_A647739CA76ED395 FOREIGN KEY (user_id)     REFERENCES "user" (id);
ALTER TABLE pending_payment ADD CONSTRAINT FK_A647739CF44CABFF FOREIGN KEY (package_id)  REFERENCES package (id);

ALTER TABLE active_session  ADD CONSTRAINT FK_ACTIVE_SESSION_USER   FOREIGN KEY (user_id)   REFERENCES "user" (id);
ALTER TABLE active_session  ADD CONSTRAINT FK_ACTIVE_SESSION_DEVICE FOREIGN KEY (device_id) REFERENCES device (id);

ALTER TABLE torrent_session ADD CONSTRAINT FK_11AF26F3A76ED395 FOREIGN KEY (user_id)     REFERENCES "user" (id);

ALTER TABLE watch_history   ADD CONSTRAINT FK_DE44EFD8A76ED395  FOREIGN KEY (user_id)     REFERENCES "user" (id) ON DELETE CASCADE;

-- -----------------------------------------------------------------------------
-- Doctrine migration bookkeeping — mark all migrations as already applied so
-- the container's `doctrine:migrations:migrate` on boot is a no-op.
-- -----------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS doctrine_migration_versions (
    version        VARCHAR(191) NOT NULL,
    executed_at    TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
    execution_time INTEGER      DEFAULT NULL,
    PRIMARY KEY (version)
);

INSERT INTO doctrine_migration_versions (version, executed_at, execution_time) VALUES
    ('DoctrineMigrations\Version20260220063748', NOW(), 0),
    ('DoctrineMigrations\Version20260220101957', NOW(), 0),
    ('DoctrineMigrations\Version20260416134613', NOW(), 0),
    ('DoctrineMigrations\Version20260630000000', NOW(), 0),
    ('DoctrineMigrations\Version20260702000000', NOW(), 0),
    ('DoctrineMigrations\Version20260710063121', NOW(), 0),
    ('DoctrineMigrations\Version20260722053848', NOW(), 0),
    ('DoctrineMigrations\Version20260728123901', NOW(), 0)
ON CONFLICT (version) DO NOTHING;

COMMIT;
