<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260722053848 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add watch_history table (WatchHistory entity)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE watch_history (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tmdb_id INT NOT NULL, type VARCHAR(20) NOT NULL, season INT DEFAULT NULL, episode INT DEFAULT NULL, imdb_id VARCHAR(30) DEFAULT NULL, title_name VARCHAR(200) DEFAULT NULL, poster_url VARCHAR(500) DEFAULT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id UUID NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DE44EFD8A76ED395 ON watch_history (user_id)');
        $this->addSql('CREATE UNIQUE INDEX user_tmdb_season_episode_unique ON watch_history (user_id, tmdb_id, type, season, episode)');
        $this->addSql('ALTER TABLE watch_history ADD CONSTRAINT FK_DE44EFD8A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE watch_history DROP CONSTRAINT FK_DE44EFD8A76ED395');
        $this->addSql('DROP TABLE watch_history');
    }
}
