-- =============================================================================
-- Delta: add the watch_history table (WatchHistory entity)
-- =============================================================================
-- Standalone, idempotent version of migration Version20260722053848.
-- Run this against a database where the Doctrine migration cannot be run
-- directly (e.g. paste into the Render dashboard SQL console, or the Supabase
-- SQL editor when DB_PROVIDER=supabase).
--
-- Already applied to the Render database (tvapp-db) via
--   php bin/console doctrine:migrations:migrate
-- so you only need this for OTHER databases / fresh provisions.
--
-- Safe to run more than once: every statement is guarded.
-- =============================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS watch_history (
    id         INT          GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tmdb_id    INT          NOT NULL,
    type       VARCHAR(20)  NOT NULL,
    season     INT          DEFAULT NULL,
    episode    INT          DEFAULT NULL,
    imdb_id    VARCHAR(30)  DEFAULT NULL,
    title_name VARCHAR(200) DEFAULT NULL,
    poster_url VARCHAR(500) DEFAULT NULL,
    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    user_id    UUID         NOT NULL,
    PRIMARY KEY (id)
);

CREATE INDEX        IF NOT EXISTS IDX_DE44EFD8A76ED395 ON watch_history (user_id);
CREATE UNIQUE INDEX IF NOT EXISTS user_tmdb_season_episode_unique
    ON watch_history (user_id, tmdb_id, type, season, episode);

-- FK (guarded — ADD CONSTRAINT has no IF NOT EXISTS in Postgres)
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_de44efd8a76ed395'
    ) THEN
        ALTER TABLE watch_history
            ADD CONSTRAINT FK_DE44EFD8A76ED395
            FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE;
    END IF;
END $$;

-- Mark the Doctrine migration as applied so the app's boot-time
-- `doctrine:migrations:migrate` treats it as a no-op.
INSERT INTO doctrine_migration_versions (version, executed_at, execution_time)
VALUES ('DoctrineMigrations\Version20260722053848', NOW(), 0)
ON CONFLICT (version) DO NOTHING;

COMMIT;
